{% set version = "0.3.3" %}

package:
  name: xbpch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xbpch/xbpch-{{ version }}.tar.gz
  sha256: cfb4df928792614cf067256161543dfbfb19013b8f140eb4ba3a90fd5fed575e

build:
  noarch: python
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - dask
    - future
    - xarray

test:
  imports:
    - xbpch

about:
  home: http://github.com/darothen/xbpch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'xarray interface for bpch files'

  description: |
    xbpch is a simple utility for reading binary-format outputs (bpch)
    used in versions of GEOS-Chem earlier than v11-02. The utility allows
    a user to load this output into an xarray/dask-powered workflow
    without having to pre-process using GAMAP, IDL, or Matlab.
  doc_url: http://xbpch.readthedocs.io/
  dev_url: https://github.com/darothen/xbpch

extra:
  recipe-maintainers:
    - darothen
