travis:
  secure:
    BINSTAR_TOKEN: vPQy16PY8apo98LY+3AlF0urIK/BmfoU+BnzDQ/li1Z5N7VLzvSnDZgaJDE48XwubDp+uijG7txSC8yo8o/9uzahNP8U6roybBiQjvmTpYDDAwYCuzqmoVMhGirvG38Fe4Pa89+nlZ+swxeZb29CsUBKU21wad7D4QZYA4R6tAw0j4+jC6E2/9CJbw9gRrRdoUmH362bQUY0yojJ3ZZb4LqkCPWG45bqLfd9vQceeDqkTMvGnZVH3ahtK0+HoRBr92+FzNeqqGQAS8UAOEZCvt0l/ez5tKNgNfWCeEWyNlhjqox2ond3pdN43JYcbOQQIr3Cmi0JksJl3WbaV02x7cPBP9owWusjb224sJjSDBVzteGN8wBW2KD6hCBEOh92MpQZeKfX20HP3OI0Bmcy71XAdg2EwCL/ri+Ix4YInUv5IjlGr6yCWB0hcYSGUpWLOjdH2aqjXjnzVXGk2iZ29Mo1qJVBg9b8gKxTR+WBNIC7HuvccxK71JQ5BrMf/mdZ69d0bG8Q+kjignymLiXwYQjsNRYy+g5MM+NfbATljHl/m+EaG0xI0hUSYIuNfUnN5w9gYqbaHWzIt5pw0fQgyXZPlHn1ZkNe9UsmzTmuILQPLHb8Vtbf8/gOqDJ7zQa+azbO2kCY4/2JKpr5auPxZiDQjycpJzf4b1Tgiym96zc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
