appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: mAdb3+5ebZdRChXEuAvJE04j31KawOH6gj1CoHSLkO6mwWirtNl7UZ3HwPGckpmztocaU+rJmkEZi2FUkxQFACS/tHTzaE0UySfbTuA2mWrpbq2Wk/1BvuDSsTwp7PCwa0zxuPot+2A7ZlKvS7H0IFso93/g5RnBOaRg1S6uNOKirayQ+6fmuvxnUiNnNUx1QqngcZYlmSnTDa11RMx5P214PJms4Tc/EzJX7zd9IvvqDvVcPQsnvC5hnR85SXDWuT05Vyufwy89PupnTzZb73OQMXrzQLyLxGDDs72rNsn2E7LG3rnNvJksHHLW1mTmSfw+0RwQ/9QqNf8CWUS3iDfNax0CNz8eOyP5vVwBikop06xnWGtokwWXwceykVPDYBb8w87Pv1Mjvoy/Cy4/J7BBp8k3eVYuE5sXKzemHwICGreyw1m1RXVnF0/7bFhJfv9SJsjF/cysOrj9mLAhL6cYB6ETub/7C/FcLJUvsvkEh0CD8u6pvmmwZfjAIRfZPRzLfkzY9g2hFs1253k9YgubYnlBQHlJcKouxYYPapXnAbsh0XNXshysyVR5e8ToJO0bYexw4/g8zL4+vIHlJ+MD9lA+B1hBrMetJdicfbnpFP+sOtIV84gFRgs15+/2uRiOO09ZNzHuosmQMRn46Y5cbkgjb6V9M8Bkbt6nvKI=}
